<template>
  <UContainer class="space-y-4">
    <div class="mt-4 p-4 border rounded">
      <p>{{ computedMessage }}</p>
    </div>
    <UButton @click="copyMessage" class="mt-2">Copy Message</UButton>
    <UForm :state="formState" @submit="generateTemplate">
      <UFormGroup label="Scholarship Percentage" name="scholarship">
        <UInput v-model="scholarship" type="number" placeholder="Enter scholarship percentage" />
      </UFormGroup>
      <UFormGroup label="Credit Points" name="creditPoints">
        <UInput v-model="creditPoints" type="number" placeholder="Enter credit points" />
      </UFormGroup>
    </UForm>

  </UContainer>
</template>

<script setup lang="ts">
import { useClipboard } from '@vueuse/core';

const scholarship = ref<number | undefined>(undefined);
const creditPoints = ref<number | undefined>(undefined);
const formState = ref({ scholarship, creditPoints });

const { copy } = useClipboard();

const computedMessage = computed(() => {
  let message = "Course tuition fees are current as of 2024. Tuition fees are subject to change and may increase each calendar year by no more than 10%. Please refer to terms and conditions on offer letter for more information.";
  
  if (scholarship.value && creditPoints.value) {
    message = `Student granted with ${scholarship.value}% scholarship and ${creditPoints.value} credit points. ${message}`;
  } else if (scholarship.value) {
    message = `Student granted with ${scholarship.value}% scholarship. ${message}`;
  } else if (creditPoints.value) {
    message = `Student granted with ${creditPoints.value} credit points. ${message}`;
  }
  
  return message;
});

const generateTemplate = () => {
  // This function is now empty as the message is generated by the computed property
};

const copyMessage = () => {
  copy(computedMessage.value);
};
</script>
